name: 🐛 Bug report
description: Create a report to help us improve profiler
title: "[BUG]: <title>"
labels: ['bug', 'untriaged']
body:
  - type: markdown
    attributes:
      value: |
        Before filing, check if this issue already exists. For usage questions, use [discussions](https://github.com/WLAN-Pi/feedback/discussions) instead.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug and what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Profiler version where this issue occurred (`profiler --version`).
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: How often does this bug happen?
      description: Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: This will be automatically formatted into code, so no need for backticks.
      value: |
        - Run `$ sudo profiler --list_interfaces`, and paste in the full output.

        - Run `$ sudo profiler --debug`, reproduce the issue, and paste in the full output.
      render: shell
    validations:
      required: true